name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 400 ssh_key.pem

        # Crear directorio ~/.ssh si no existe
        mkdir -p ~/.ssh

        # Agregar la clave del host al archivo known_hosts
        ssh-keyscan -H ec2-54-200-96-222.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

        # Copiar archivos a la instancia EC2
        scp -i ssh_key.pem -r ./ ubuntu@ec2-54-200-96-222.us-west-2.compute.amazonaws.com:/

        # Conectar y ejecutar comandos en la instancia EC2
        ssh -i ssh_key.pem ubuntu@ec2-54-200-96-222.us-west-2.compute.amazonaws.com 'cd / && npm install && pm2 reload ecosystem.config.js --env production'

        # Limpiar
        rm ssh_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
